/**
 * Each new term in the Fibonacci sequence is generated by adding the previous two terms. 
 * By starting with 1 and 2, the first 10 terms will be:
   1, 2, 3, 5, 8, 13, 21, 34, 55, 89, 
  By considering the terms in the Fibonacci sequence whose values do not exceed four million, 
  find the sum of the even-valued terms.
 */
const fibonacci=n=>{
 const fib=[0,1];
 for (let i = 2; i <= n; i++) {
    fib[i]=fib[i-2]+fib[i-1];
    
 }
 return fib[n];
}
console.log(fibonacci(34));